### PR TITLE
Fix sample of Logger

### PR DESCRIPTION
**Pull request by tubo28**
- Change the name of a variable `log` -> `logger`
- Merge two samples into one
- Fix a message that seems wrong

### CODE REVIEW

**Comment by sho-h** [comment]
> * Change the name of a variable log -> logger

I like logger, too.

> * Merge two samples into one

I like only one sample. It's simple. And Ruby's logger sample is already merged.

> * Fix a message that seems wrong

Original message seems correct. Not `existing` but `exiting`. I think only this point should be fixed.

**Comment by tubo28** [comment]
I fixed the message, sorry.

>I like logger, too.

I changed it because the name was `log` at first but `logger` bellow, so it had caused undefined local variable error, not non-existent error.

**Comment by sho-h** [comment]
>> I like logger, too.
>
> I changed it because the name was log at first but logger bellow, so it had caused undefined local variable error, not non-existent error.

Sorry. Variable name was changed on the way.

**Comment by znz** [comment]
Thanks!

**Pull request merged**
